spring.application.name=flink-jobs
mysql.hostname=rm-wz9u5z016py624uz9uo.mysql.rds.aliyuncs.com
mysql.database=flink_test
mysql.table=


hive.metastore.uris=
clickhouse.url=


kafka.bootstrap-servers=192.168.31.201:9092